html
orlovaad/Axion pull request #1
Opened 2022-02-28 09:43 UTC by orlovaad

2022-03-14 15:18 UTC, agatta17 requested changes

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +          <a href="#"><img src="images/flag-rus.png" alt="Flag Russia" width="20px" href="20px"></a>
почему usa кнопкой, а тут ссылки?

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +      <div class="menu__language">
блок не находится в menu, поэтому menu__ лучше убрать из названия класса

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +      <label class="menu__btn" for="menu__toggle">
класс не по БЭМ, элемент лежит в блоке hamburger-menu

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +        <div class="model__price-color">
попробуй более общее название класса придумать, со временем туда может еще какая-то инфа о товаре добавляться

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +      <div class="model__line"></div>
линия вне блока model

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +      <div class="video__foto"><img src="images/video.jpg"  alt="Video preview" ></div>
для чего контейнер video__foto? ему не заданы стили

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +            <footer>
у тега footer нет стилей, он точно нужен?

2022-03-14 15:18 UTC, agatta17 commented on index.html
> +                    <p class="footer__subtitle">Login</p>
footer__link

2022-03-14 15:18 UTC, agatta17 commented on style.css
> +.arrow div {
лучше не мешать классы и теги, если используешь БЭМ

2022-03-20 14:36 UTC, orlovaad commented on index.html
> +      <div class="menu__language">
он вроде как в menu-right

2022-03-20 14:36 UTC, orlovaad commented on index.html
> +      <label class="menu__btn" for="menu__toggle">
удалила этот блок

2022-03-20 14:51 UTC, orlovaad commented on index.html
> +            <footer>
убрала

2022-03-20 16:17 UTC, agatta17 approved these changes

2022-03-20 17:04 UTC, merged